### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by okkdev** [crisidev/homebrew-chunkwm#10]
When trying to install this happens: 
` brew install chunkwm                                                                                                                                     18s
==> Installing chunkwm from crisidev/chunkwm
==> Downloading https://github.com/koekeishiya/chunkwm/archive/v0.2.30.tar.gz
==> Downloading from https://codeload.github.com/koekeishiya/chunkwm/tar.gz/v0.2.30
######################################################################## 100.0%
==> make install
==> make
==> make install
Last 15 lines from /Users/pomf/Library/Logs/Homebrew/chunkwm/03.make:
install

rm -f ./../../../plugins/tiling.so
mkdir -p ./../../../plugins
clang++ plugin.mm -O2 -std=c++11 -Wall -Wno-deprecated -Wno-writable-strings -o ../../../plugins/tiling.so -shared -fPIC -framework Carbon -framework Cocoa -framework ApplicationServices
In file included from plugin.mm:35:
./../../common/border/border.mm:76:51: error: use of undeclared identifier 'NSWindowStyleMaskBorderless'
                                       styleMask: NSWindowStyleMaskBorderless
                                                  ^
In file included from plugin.mm:48:
./presel.mm:89:51: error: use of undeclared identifier 'NSWindowStyleMaskBorderless'
                                       styleMask: NSWindowStyleMaskBorderless
                                                  ^
2 errors generated.
make: *** [../../../plugins/tiling.so] Error 1
`

**Comment by crisidev** [comment]
Which version of osx are you running? This looks like https://github.com/koekeishiya/chunkwm/issues/186

Can you try to install the HEAD version of chunkwm with

```brew install --HEAD chunkwm```

?

**Comment by okkdev** [comment]
Thanks that worked. I am on 10.11.
