### ISSUE TITLE
Can't build from brew

### ISSUE THREAD

**Issue by natsumi** [crisidev/homebrew-chunkwm#12]
Getting a syntax error in the chunkwm.rb forumla:

`❯ brew install --HEAD chunkwm
Error: chunkwm: /usr/local/Homebrew/Library/Taps/crisidev/homebrew-chunkwm/chunkwm.rb:80: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/crisidev/homebrew-chunkwm/chunkwm.rb:83: syntax error, unexpected *
        * Edit ~/.chunkwmrc and change line
         ^`

**Comment by crisidev** [comment]
Hum.. This is weird.. This is line 83 of chunkwm.rb: https://github.com/crisidev/homebrew-chunkwm/blob/master/chunkwm.rb#L83 and it is clean :)

I guess you have a local git conflict inside the tap.

Can you try to untap the repo, tap it again and reinstall?

**Comment by natsumi** [comment]
Good call!  

I'm not sure how I ended up in this state, but untapping and tapping again resolved the problem.  

Thanks.

**Comment by crisidev** [comment]
No problem! :)
