### ISSUE TITLE
Error: Permission denied @ dir_s_mkdir - /usr/local/var/log/chunkwm

### ISSUE THREAD

**Issue by confluencepoint** [crisidev/homebrew-chunkwm#22]
I get the following error message:
`Error: Permission denied @ dir_s_mkdir - /usr/local/var/log/chunkwm`
when I try to install `chunkwm` (OS X 10.11.6) with the following parameters:
`brew install --HEAD --with-tmp-logging chunkwm`

_Someone a tip for troubleshooting?_
Install reference: [http://hde-advent-2017.hatenadiary.jp/entry/2017/12/24/000000](http://hde-advent-2017.hatenadiary.jp/entry/2017/12/24/000000)

**Comment by crisidev** [comment]
This looks like a problem with your brew installation... I have never had this problem. Can you show me the permissions of `/usr/local/var` and `/usr/local/var/log` ?

Anyway, the `--with-tmp-logging` option is deprecated from version 3.3 since chunkwm supports it through `chunwc` configuration option.

**Comment by confluencepoint** [comment]
```
$:ls -aled /usr/local/var
drwxr-xr-x  8 kp  admin  272 31 Jan 03:07 /usr/local/var

$:ls -aled /usr/local/var/log
drwxr--r--  2 root  admin  68 12 Sep  2016 /usr/local/var/log
```

**Comment by crisidev** [comment]
Sorry for leaving this issue open for a lot of time :( IS this still happening to you?

**Comment by amoeba** [comment]
Hey @crisidev I'm seeing this after a `brew install chunkwm`. I'm on Mojave beta so I didn't expect this to work without issues but I thought I'd (1) offer to help you debug if you still have interest and (2) provide a little more log detail.

I have Xcode beta running and the matching beta CLI tools from developer.apple so other Homebrew stuff is compiling just fine. After the first install failure, I ran `sudo chown -R (whoami) /usr/local` and ran again with the same failure. I'm happy to help with any debug output.

<details>
<summary>`brew install chunkwm` output</summary>

```
❯ brew install chunkwm
Updating Homebrew...
==> Installing chunkwm from crisidev/chunkwm
==> Downloading https://github.com/koekeishiya/chunkwm/archive/v0.4.2.tar.gz
Already downloaded: /Users/bryce/Library/Caches/Homebrew/chunkwm-0.4.2.tar.gz
==> make install
Last 15 lines from /Users/bryce/Library/Logs/Homebrew/chunkwm/01.make:
make
install

rm -rf ./bin
mkdir -p ./bin
clang++ src/core/chunkwm.mm -O2 -std=c++11 -Wall -Wno-deprecated -o bin/chunkwm -rdynamic -ldl -lpthread -framework Carbon -framework Cocoa -framework ScriptingBridge
In file included from src/core/chunkwm.mm:31:
src/core/../common/accessibility/display.mm:33:25: error: use of undeclared identifier 'CGDisplayCreateUUIDFromDisplayID'
    CFUUIDRef UUIDRef = CGDisplayCreateUUIDFromDisplayID(Id);
                        ^
src/core/../common/accessibility/display.mm:355:29: error: use of undeclared identifier 'CGDisplayCreateUUIDFromDisplayID'
    CFUUIDRef DisplayUUID = CGDisplayCreateUUIDFromDisplayID(DisplayID);
                            ^
2 errors generated.
make: *** [bin/chunkwm] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Error: Permission denied @ dir_s_mkdir - /usr/local/var/log/chunkwm https://github.com/crisidev/homebrew-chunkwm/issues/22

Error: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```
</summary>

**Comment by crisidev** [comment]
Unfortunately your issue is not related with this one. Since you are on Mojave, there have been an API change. There is a way to install chunkwm on Mojave thou: see https://github.com/koekeishiya/chunkwm/issues/439

**Comment by amoeba** [comment]
Ah. Gotcha. Thanks!

**Comment by dominiklohmann** [comment]
Closing as I consider this resolved.
