### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by asmvik** [crisidev/homebrew-chunkwm#23]
For what it's worth, logging can now be controlled directly in chunkwm's configfile.

`chunkc core::log_level none` if you want logging disabled

`chunkc core::log_file /path/to/file` to specify a file (only on master currently, defaults to stdout).

With the next release logging should not need to be handled explicitly in the brew formulae.

**Comment by crisidev** [comment]
I will remove it. Thanks for the info.

**Comment by crisidev** [comment]
Fixed with version 3.3
