### ISSUE TITLE
Typo in formula

### ISSUE THREAD

**Issue by jer-irl** [crisidev/homebrew-chunkwm#4]
I only report because it tripped me up a little.  
```
Plugins are installed into /usr/local/opt/chunkwm/share/chunkwm_plusing folder.
```
should have the folder `/usr/local/opt/chunkwm/share/chunkwm_plugins` instead (plugins is misspelled)

**Comment by crisidev** [comment]
I will fix it ASAP. Thanks for reporting it!

**Comment by crisidev** [comment]
Resolved.
