### ISSUE TITLE
Homebrew Installation

### ISSUE THREAD

**Issue by knightjp** [crisidev/homebrew-chunkwm#5]
@crisidev As requested, I am opening an issue over here.

As I understand it.. I have to use `brew tap crisidev/homebrew-chunkwm` and then `brew install chunkwm`
Am I correct?

**Comment by crisidev** [comment]
Yes, correct. The first command ```brew tap crisidev/homebrew-chunkwm``` dowloads the new formula, the second one install it.

**Comment by crisidev** [comment]
@knightjp Is this working for you? Can I close the issue?

**Comment by knightjp** [comment]
Yes... the installation instructions really did work. But unfortunately `chunkwm` did not work out for me. I am going back to `kwm` until I this is finally ready as a finished product. 
Maybe it is the chunkwmrc.

**Comment by knightjp** [comment]
@crisidev Are you currently using Chunkwm or still on KWM?

**Comment by crisidev** [comment]
I am currently using chunkwm. I still have some problems, but I adapted my workspaces to chunkwm quirks and I am fine with it. Why?

**Comment by knightjp** [comment]
I have posted some issues with chunkwm, but I can't see much of an improvement with the new version. Maybe it is my settings in the chunkwmrc file. 
I have windows bouncing in from monitor to monitor whenever I open a new one. For instance, whenever I open Firefox and its on Monitor 2... when I launch safari, all of a sudden both apps on running on split screen on monitor 1. That's not what I want. 

Åsmund aka koekeishiya says that he has never faced this issue, but I guess it is because he does not use a dual monitor setup like I do. I'm wondering if I would be having any of my issues if installed chunkwm from source rather than using home-brew.

**Comment by crisidev** [comment]
The homebrew installation is following the source repo, hence the code is not different. Homebrew is just a packaging mechanism.

Regarding your problems, I don't know how to help. I am currently using the laptop monitor + an external one and all the applications has rules to be positioned in particular desktop numbers. I am not having a lot of issues and it is more performant than kwm.

**Comment by crisidev** [comment]
Also chunkwm is a framework. It takes a while to find the proper settings and to adapt your workflow.

Are you using customs settings or only the one provided on the repo as examples?

**Comment by knightjp** [comment]
I'm using my own edited file. Here is my chunkwmrc at this moment.. 

```#!/bin/bash

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir ~/.chunkwm_plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                bsp
chunkc set 5_desktop_mode                bsp

chunkc set 1_desktop_tree                ~/.chunkwm_layouts/dev_1

chunkc set global_desktop_offset_top     2
chunkc set global_desktop_offset_bottom  2
chunkc set global_desktop_offset_left    2
chunkc set global_desktop_offset_right   2
chunkc set global_desktop_offset_gap     2

chunkc set 1_desktop_offset_top          2
chunkc set 1_desktop_offset_bottom       2
chunkc set 1_desktop_offset_left         2
chunkc set 1_desktop_offset_right        2
chunkc set 1_desktop_offset_gap          2

chunkc set 3_desktop_offset_top          2
chunkc set 3_desktop_offset_bottom       2
chunkc set 3_desktop_offset_left         2
chunkc set 3_desktop_offset_right        2

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5
chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           1
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#
# chunkc set mouse_modifier              \"cmd shift\"
chunkc set mouse_modifier                fn

chunkc set preselect_border_color        0xffffff00
chunkc set preselect_border_width        4
chunkc set preselect_border_radius       0

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.5

#
# NOTE: the following are config variables for the chunkwm-border plugin.
#

chunkc set focused_border_color          0xffc0b18b
chunkc set focused_border_width          4
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  0

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

chunkc core::load tiling.so
chunkc core::load ffm.so
#chunkc core::load border.so

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#

chunkc tiling::rule --owner \"System Preferences\" --subrole AXStandardWindow --state tile
chunkc tiling::rule --owner Finder --name Copy --state float```

**Comment by knightjp** [comment]
![screen shot 2017-08-01 at 5 40 28 pm](https://user-images.githubusercontent.com/14360736/28833787-796b6dfc-76f1-11e7-883b-46f63ee473d8.png)
Has this ever happened to you?

**Comment by crisidev** [comment]
No, never.

**Comment by knightjp** [comment]
Happens to me quite a bit. Can't think of why... I always have to restart it to get it back. Otherwise all the windows open up that size in the same position
