### ISSUE TITLE
.chunkwmrc permissions denied

### ISSUE THREAD

**Issue by grounded042** [crisidev/homebrew-chunkwm#6]
Not sure if this should go into the actual chunkwm repo, but when I start the service via `brew services start chunkwm` I get the following in `/tmp/chunkwm.err`: `sh: /Users/grounded042/.chunkwmrc: Permission denied`. I tried restarting the service after enabling accessibility and also restarted my Mac, but the problem persists. Any thoughts?

**Comment by grounded042** [comment]
For what it's worth, the permissions on that file are `-rw-r--r--`

**Comment by crisidev** [comment]
How did you copied the file in your home dir?

Can you post the result of 
```ls -l $HOME/.chunkwmrc```

?

**Comment by grounded042** [comment]
I created the new file in a text editor and copied the raw config from the example on the chunkwm repo.

Here is the command output: 
`-rw-r--r--  1 grounded042  grounded042  2908 Jul 10 11:49 /Users/grounded042/.chunkwmrc`

**Comment by asmvik** [comment]
.chunkwmrc is a shell script, so it needs executable permissions. (755)

Just `chmod +x ~/.chunkwmrc`

I suppose that could be made explicit in the install instructions. I have sort of taken it for granted as the shell script part is mentioned.

**Comment by grounded042** [comment]
Ah, I should have known considering it had the `#!/bin/bash` line. Working great now!
